stage: ${env.STAGE}
jampick-web:
  component: "@sls-next/serverless-component@3.2.0"
  inputs:
    useServerlesstrace: false
    policy: arn:aws:iam::159698424543:policy/jampickweb-policy
    bucketName: ${env.${stage}_bucket_name}
    buckerRegion: ap-northeast-2
    cloudfront:
      distributionId: ${env.${stage}_cloudfront}
    name:
      defaultLambda: ${env.${stage}_default_lambda}
      apiLambda: ${env.${stage}_api_lambda}
      imageLambda: ${env.${stage}_image_lambda}
